name = "sea-battle-api"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[vars]
API_ENV = "local"
MONAD_RPC_URL = "https://rpc.monad.xyz"

[[d1_databases]]
binding = "DB"
database_name = "sea-battle"
database_id = "eb61f922-f915-4ab9-8a49-87b374e0f148"
